### PR TITLE
Added array-loop doc

### PR DESCRIPTION
**Pull request by BlackGoku36**
Added array-loop.jpeg and doc for it

### CODE REVIEW

**Comment by luboslenco** [comment]
Sorry there are typos in it.:(

**Comment by BlackGoku36** [comment]
what kind of typos? i know i bymistakely wrote assets as assests.

**Comment by BlackGoku36** [comment]
I am adding almost all logic type node now. If there something wrong, can you tell me plz.

**Comment by BlackGoku36** [comment]
Can we show documentation in this order
nodes_order

If not then what order should we show in?

**Comment by luboslenco** [comment]
You can just run it through some spell-checker, for example there is 'assingned '.:) Yes, that order should be fine. Thanks for help!

**Pull request merged**
