### PR TITLE
FAQ and Common pitfalls

### PR DESCRIPTION
**Pull request by BlackGoku36**
Added FAQ and Common pitfalls as requested in forums http://forums.armory3d.org/t/faq-the-top-things-i-wish-i-knew-when-starting-with-armory/2871

Added Credits thing, I thought it was good thing to credit people, I can remove it if it is not necessary
and some fix

### CODE REVIEW

**Comment by luboslenco** [comment]
Sweet!

For the credits - it is important and it would be the best if each author did his own PR, to get properly credited for his contribution:
https://github.com/armory3d/armory_docs/graphs/contributors

Otherwise when someone else updates the doc and forgets to manually update credits confusing things will happen. (original author signed under the doc which he did not write etc.)

**Comment by Bugsbane** [comment]
@luboslenco Agreed where devs and more technical users are concerned. Being a forum post primarily for new users though, there are going to be contributions from people who don't use github. Many would be intimidated by the process of creating and submitting pull requests. In cases like that we're probably going to have to have someone familiar with GitHub turn their forum contribution into a PR for them.

Heck, even here, although I wrote most of the content of that post, and I *am* comfortable with creating a pull request, I am still grateful to @BlackGoku36 for doing the work of turning my content into a PR. After all, I'm just trying to help grow the community, not build a GitHub resume.

**Comment by zicklag** [comment]
I'm kind of agreeing with @Bugsbane at least in this instance, where I have contributed the ideas for some of the things to include in this page, but @Bugsbane has done the actual aggregation of the ideas I suggested for the forum topic and @BlackGoku36 has compiled it for the Armory docs. If I were to submit a PR, I would be copying and pasting paragraphs that @Bugsbane has written and @BlackGoku36 has formatted. Mentioning people who helped in commit might be a good way to handle credit? It would be nice if GitHub let you add people to the commit who helped.

Either way, this does bring up a good point about the documentation in general. This page is something that a lot of people could contribute ideas to and it might be better to make the FAQ, at least, a Wiki page. Discourse has a feature to turn the topic into a wiki page, but I don't know exactly what it does. We could maybe test it, or put the FAQ on the GitHub wiki so that other people could more easily edit it and then we just link to that page from the docs site. That way we it would be super easy for everybody to contribute to the list without having to use Git or anything more technical than Markdown, which everyone is using on the Forum already. Just a thought. :man_shrugging:

**Comment by BlackGoku36** [comment]
So what should I do? Revert commit to original?
Maybe we could have two separate credit system like, Contributors (who edit the docs, people mentioned in contributors will be the one who submitted PR) and Thanks(Who helped with ideas, people mentions in thanks can be from forums or discord like @Bugsbane and @zicklag are saying)
I could edit the [contributing doc](https://armory3d.org/manual/#/dev/contribute)
how that idea @luboslenco ? or we could remove credit system altogether i don't have problem with that

**Comment by Bugsbane** [comment]
I'm fine with submitting my changes as pull requests. I just have a feeling this could get messy with conflicts, really quickly if a bunch of us are all trying to make commits to the same file if Lubos doesn't have time to review and commit the pull requests as fast as we submit them...

Maybe someone(s) who is active here could also be made a team member to approve commits, just on armory_docs? The idea here is for us all to be able to help the project out and take some of the workload *off* Lubos, rather than to add more work to Lubos' todo list...

@luboslenco ?

**Comment by luboslenco** [comment]
I am happy to broaden the members here if anyone is willing to take on that! We just need someone who has been around for a bit and can do some text formatting/check for typos when needed.

If there is interest we can also find someone to help with the examples repo and more. The pull-request frequency is not high in those yet but perhaps we can boost that with additional maintainers.🙂

**Comment by BlackGoku36** [comment]
Count me in for examples and docs repos 👍
We need like 2 Active people in minimum, like when any maintainers push commit other just approve it by reacting it with `👍 ` so that it is marked as checked for typos, mis-information(when someone got something wrong), etc, and approving these commit would not take much time as it is maintained by `Active` peoples, should take less than day

**Comment by Bugsbane** [comment]
Sounds good. I'd like to volunteer for examples and docs repos, too.

**Comment by luboslenco** [comment]
Trying out the wiki approach, everyone can contribute freely without approval now at https://github.com/armory3d/armory/wiki.

**Pull request merged**
